version: '3'
services:
  frontend:
    image: node:19.5
    container_name: lori-frontend
    working_dir: /frontend/source/src
    command: ["tail", "-f", "/dev/null"] # To keep the container running
    ports:
      - "4443:443"
      - "8808:80"
    volumes:
      - ${FRONTEND_SRC_PATH}:/frontend:rw
      # - ./frontend/ssl/lori-app.crt:/etc/ssl/certs/site.crt
      # - ./frontend/ssl/lori-app.key:/etc/ssl/private/site.dec.key

  backend:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    command: ["tail", "-f", "/dev/null"] # To keep the container running
    container_name: lori-backend
    volumes:
      - ${BACKEND_SRC_PATH}:/backend:rw

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'lori'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    # Where our data will be persisted
    volumes:
      - db:/var/lib/mysql

volumes:
  db: